name: 'greencard_analytics'
version: '1.0.0'
config-version: 2
profile: 'lakehouse'

model-paths: ["models"]
test-paths: ["tests"]

models:
  greencard_analytics:
    staging:
      +materialized: table
      +schema: staging
      +properties:
        format: "'PARQUET'"
        
    intermediate:
      +materialized: table
      +schema: intermediate
      +properties:
        format: "'PARQUET'"
        
    marts:
      +materialized: table
      +schema: marts
      +properties:
        format: "'PARQUET'"
        partitioning: "ARRAY['month(order_date)']"
        sorted_by: "ARRAY['order_date', 'customer_id']"